
package Proyecto;



// importacion de las librerias que estamos utilizando en el programa
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Formatter;
import java.util.Properties;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */

public class Registro extends javax.swing.JFrame {
    
    
    
    //ArrayList<Empleado> lista=new ArrayList<>();
   // DefaultTableModel modelo=new DefaultTableModel ();
    
    // declaramos variables para crear el Registro para poder guaradar 
    String barra=File.separator;
    // el nombre y la ubicacion donde van estar nuestros registros 
    String  ubicacion= System.getProperty("user.dir")+barra+"Registro"+barra;

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        // nos permite que el Jframe se nos ubique en el centro de la pantalla
        this.setLocationRelativeTo(null);
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblcedula = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbltecnico = new javax.swing.JLabel();
        lblhorasextras = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txthorasextras = new javax.swing.JTextField();
        lbltotalingreso = new javax.swing.JLabel();
        lbltotalegreso = new javax.swing.JLabel();
        lbltotalrecibir = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        btnaceptar = new javax.swing.JButton();
        txttotalrecibir = new javax.swing.JTextField();
        txttotalegreso = new javax.swing.JTextField();
        txttotalingreso = new javax.swing.JTextField();
        lblbonoproduccion = new javax.swing.JLabel();
        txtbonoproduccion = new javax.swing.JTextField();
        lblanticipos = new javax.swing.JLabel();
        lblsancion = new javax.swing.JLabel();
        txtanticipos = new javax.swing.JTextField();
        txtsancion = new javax.swing.JTextField();
        lblbonoperfil = new javax.swing.JLabel();
        txtbonoperfil = new javax.swing.JTextField();
        lblbonoproduccion1 = new javax.swing.JLabel();
        txtbonoproduccion1 = new javax.swing.JTextField();
        lblsueldo = new javax.swing.JLabel();
        txtsueldo = new javax.swing.JTextField();
        lblaporteiess = new javax.swing.JLabel();
        txtaporteiess = new javax.swing.JTextField();
        lblsancion1 = new javax.swing.JLabel();
        txtsancion1 = new javax.swing.JTextField();
        lblhorasextras1 = new javax.swing.JLabel();
        txthorasextras1 = new javax.swing.JTextField();
        lblanticipos1 = new javax.swing.JLabel();
        txtanticipos1 = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        boxtecnico = new javax.swing.JComboBox<>();
        lbltecnico1 = new javax.swing.JLabel();
        txttecnico1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaempleado = new javax.swing.JTable();
        boxidioma = new javax.swing.JComboBox<>();
        lblidioma = new javax.swing.JLabel();
        btnguardar1 = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("registro");
        setMinimumSize(new java.awt.Dimension(940, 582));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("           Calculo Sueldo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 0, 190, 34);

        lblnombre.setText(" Nombres");
        getContentPane().add(lblnombre);
        lblnombre.setBounds(30, 60, 83, 20);

        lblcedula.setText("Cedula");
        getContentPane().add(lblcedula);
        lblcedula.setBounds(30, 130, 110, 14);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(42, 179, 0, 0);

        lbltecnico.setText("Tecnico");
        getContentPane().add(lbltecnico);
        lbltecnico.setBounds(30, 170, 82, 14);

        lblhorasextras.setText("Horas");
        getContentPane().add(lblhorasextras);
        lblhorasextras.setBounds(30, 210, 77, 22);

        txtnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombresActionPerformed(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombres);
        txtnombres.setBounds(142, 53, 131, 30);

        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });
        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtcedula);
        txtcedula.setBounds(142, 125, 131, 30);

        txthorasextras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthorasextrasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthorasextrasKeyTyped(evt);
            }
        });
        getContentPane().add(txthorasextras);
        txthorasextras.setBounds(140, 200, 130, 30);

        lbltotalingreso.setText("Total ingreso");
        getContentPane().add(lbltotalingreso);
        lbltotalingreso.setBounds(313, 192, 97, 14);

        lbltotalegreso.setText("Total egreso");
        getContentPane().add(lbltotalegreso);
        lbltotalegreso.setBounds(571, 192, 90, 14);

        lbltotalrecibir.setText("  Total recibir");
        getContentPane().add(lbltotalrecibir);
        lbltotalrecibir.setBounds(580, 260, 100, 14);

        lblapellido.setText("Apellidos");
        getContentPane().add(lblapellido);
        lblapellido.setBounds(30, 100, 83, 14);

        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });
        getContentPane().add(txtapellidos);
        txtapellidos.setBounds(141, 90, 130, 30);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(532, 125, 274, 0);

        lbltotal.setAutoscrolls(true);
        getContentPane().add(lbltotal);
        lbltotal.setBounds(398, 125, 0, 0);

        btnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1472643693_accept.png"))); // NOI18N
        btnaceptar.setText("Aceptar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });
        btnaceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnaceptarKeyPressed(evt);
            }
        });
        getContentPane().add(btnaceptar);
        btnaceptar.setBounds(310, 300, 140, 40);
        getContentPane().add(txttotalrecibir);
        txttotalrecibir.setBounds(680, 250, 90, 30);

        txttotalegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalegresoActionPerformed(evt);
            }
        });
        getContentPane().add(txttotalegreso);
        txttotalegreso.setBounds(680, 180, 90, 30);
        getContentPane().add(txttotalingreso);
        txttotalingreso.setBounds(430, 190, 88, 30);

        lblbonoproduccion.setText("Bono Producción");
        getContentPane().add(lblbonoproduccion);
        lblbonoproduccion.setBounds(30, 250, 99, 14);

        txtbonoproduccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbonoproduccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbonoproduccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtbonoproduccion);
        txtbonoproduccion.setBounds(140, 240, 130, 30);

        lblanticipos.setText("Anticipos");
        getContentPane().add(lblanticipos);
        lblanticipos.setBounds(30, 290, 93, 14);

        lblsancion.setText("Sanción");
        getContentPane().add(lblsancion);
        lblsancion.setBounds(30, 330, 93, 14);

        txtanticipos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtanticiposKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtanticiposKeyTyped(evt);
            }
        });
        getContentPane().add(txtanticipos);
        txtanticipos.setBounds(140, 280, 130, 30);

        txtsancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsancionActionPerformed(evt);
            }
        });
        txtsancion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsancionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsancionKeyTyped(evt);
            }
        });
        getContentPane().add(txtsancion);
        txtsancion.setBounds(140, 320, 130, 30);

        lblbonoperfil.setText("Bono Perfil");
        getContentPane().add(lblbonoperfil);
        lblbonoperfil.setBounds(313, 97, 110, 14);
        getContentPane().add(txtbonoperfil);
        txtbonoperfil.setBounds(430, 90, 88, 30);

        lblbonoproduccion1.setText("Bono Producción");
        getContentPane().add(lblbonoproduccion1);
        lblbonoproduccion1.setBounds(313, 128, 120, 14);

        txtbonoproduccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbonoproduccion1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtbonoproduccion1);
        txtbonoproduccion1.setBounds(430, 120, 88, 30);

        lblsueldo.setText("Sueldo");
        getContentPane().add(lblsueldo);
        lblsueldo.setBounds(313, 66, 70, 14);
        getContentPane().add(txtsueldo);
        txtsueldo.setBounds(430, 60, 88, 30);

        lblaporteiess.setText("Aporte IESS");
        getContentPane().add(lblaporteiess);
        lblaporteiess.setBounds(571, 66, 110, 14);
        getContentPane().add(txtaporteiess);
        txtaporteiess.setBounds(680, 60, 90, 30);

        lblsancion1.setText("Sanción");
        getContentPane().add(lblsancion1);
        lblsancion1.setBounds(570, 100, 63, 14);
        getContentPane().add(txtsancion1);
        txtsancion1.setBounds(680, 90, 90, 30);

        lblhorasextras1.setText("Horas Extras");
        getContentPane().add(lblhorasextras1);
        lblhorasextras1.setBounds(313, 159, 97, 14);
        getContentPane().add(txthorasextras1);
        txthorasextras1.setBounds(430, 150, 88, 30);

        lblanticipos1.setText("Anticipos");
        getContentPane().add(lblanticipos1);
        lblanticipos1.setBounds(570, 130, 81, 14);
        getContentPane().add(txtanticipos1);
        txtanticipos1.setBounds(680, 120, 90, 30);

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquette1.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(470, 300, 140, 40);

        boxtecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargo", "Ayudante", "Junior", "Senor", "Master" }));
        boxtecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxtecnicoActionPerformed(evt);
            }
        });
        boxtecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxtecnicoKeyPressed(evt);
            }
        });
        getContentPane().add(boxtecnico);
        boxtecnico.setBounds(140, 160, 130, 30);

        lbltecnico1.setText("Tecnico");
        getContentPane().add(lbltecnico1);
        lbltecnico1.setBounds(330, 260, 64, 14);
        getContentPane().add(txttecnico1);
        txttecnico1.setBounds(430, 250, 90, 30);

        tablaempleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaempleado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 360, 900, 150);

        boxidioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        boxidioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxidiomaActionPerformed(evt);
            }
        });
        getContentPane().add(boxidioma);
        boxidioma.setBounds(800, 20, 100, 20);

        lblidioma.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblidioma.setForeground(new java.awt.Color(51, 51, 51));
        lblidioma.setText("Idioma");
        getContentPane().add(lblidioma);
        lblidioma.setBounds(720, 20, 80, 20);

        btnguardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquette1.png"))); // NOI18N
        btnguardar1.setText("Guardar");
        btnguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar1);
        btnguardar1.setBounds(470, 300, 140, 40);

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar);
        btnbuscar.setBounds(620, 300, 120, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/climatizacion (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 940, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombresActionPerformed

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        //Con este metodo verificamos que todos los campos esten completamente llenos
        camposblancos();
        
         
            
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void txttotalegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalegresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalegresoActionPerformed

    private void txtsancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsancionActionPerformed

    private void txtbonoproduccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbonoproduccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbonoproduccion1ActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
         // nos permite identificar el idioma y dar el respectivo mensaje en el idioma asignado
         // de acuerdo al idioma enviar el mensaje correspondiente
        String idioma;
        idioma=boxidioma.getSelectedItem().toString();
        if(idioma.equals("Español")||idioma.equals("Spanish")){
            // cumplida la condicion con este metodo guardamos el archivo
            guardar();
            JOptionPane.showMessageDialog(null," Archivo Guardado ","",JOptionPane.INFORMATION_MESSAGE);   
        }else{ 
            //cumplida la condicion con este metodo guardamos el archivo 
            guardar();
            JOptionPane.showMessageDialog(null," Saved File ","",JOptionPane.INFORMATION_MESSAGE);   
        }
         
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txthorasextrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthorasextrasKeyPressed
        
        // nos permite que con la tecla enter seguir al siguiente campo 
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String idioma;
            // de acuerdo al idioma enviar el mensaje correspondiente
            idioma=boxidioma.getSelectedItem().toString();
            // mientras el campo no este lleno no envia el mensaje
            if((idioma.equals("English"))&&(txthorasextras.getText().equals(""))){
                JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);
            }else{
                // mientras el campo no este lleno no envia el mensaje
                if (txthorasextras.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Llene Campos ","",JOptionPane.ERROR_MESSAGE);   
                }else{
                    // mientaras el campo este lleno continuamos al siguiente
                    txtbonoproduccion.requestFocus();   
                }
                
            }
            
            
        }
    }//GEN-LAST:event_txthorasextrasKeyPressed

    private void boxtecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxtecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxtecnicoActionPerformed

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        // permite el ingreso de solo valores numericos en el campo
        char c= evt.getKeyChar();
        if(c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txthorasextrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthorasextrasKeyTyped
        // permite el ingreso de solo valores numericos en el campo
        char c= evt.getKeyChar();
        if(c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txthorasextrasKeyTyped

    private void txtbonoproduccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbonoproduccionKeyTyped
        // permite el ingreso de solo valores numericos en el campo
        char c= evt.getKeyChar();
        if(c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtbonoproduccionKeyTyped

    private void txtanticiposKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanticiposKeyTyped
        // permite el ingreso de solo valores numericos en el campo
        char c= evt.getKeyChar();
        if(c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtanticiposKeyTyped

    private void txtsancionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsancionKeyTyped
        // permite el ingreso de solo valores numericos en el campo
        char c= evt.getKeyChar();
        if(c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtsancionKeyTyped

    private void txtnombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyPressed
        // nos permite que con la tecla enter seguir al siguiente campo 
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            // declaramos una variable String
            String idioma;
            // de acuerdo al idioma enviar el mensaje correspondiente
            idioma=boxidioma.getSelectedItem().toString();
            if((idioma.equals("English"))&&(txtnombres.getText().equals(""))){
                JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);
            }else{
                if (txtnombres.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Llene Campos","",JOptionPane.ERROR_MESSAGE);   
                }else{
                  txtapellidos.requestFocus();  
                }   
            }   
        }
    }//GEN-LAST:event_txtnombresKeyPressed

    private void txtapellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyPressed
        // Nos permite que con solo la tecla enter continue al siguiente campo
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){  
            String idioma;
            idioma=boxidioma.getSelectedItem().toString();
            //Nos permite validar que los campos esten llenos ademas nos permite mostrar el mensaje de error
            if((idioma.equals("English"))&&(txtapellidos.getText().equals(""))){
                JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);
            }else{
                if (txtapellidos.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Llene Campos ","",JOptionPane.ERROR_MESSAGE);   
                }else{
                  txtcedula.requestFocus();  
                }    
            }
        }
    }//GEN-LAST:event_txtapellidosKeyPressed

    private void txtcedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyPressed
        // Nos permite que con solo la tecla enter continue al siguiente campo
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String idioma;
            idioma=boxidioma.getSelectedItem().toString();
            //Nos permite validar que los campos esten llenos ademas nos permite mostrar el mensaje de error
            if(idioma.equals("English")&&txtcedula.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);
            }else{
                if (txtcedula.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Llene Campos ","",JOptionPane.ERROR_MESSAGE);   
                }else{
                validacionCedula(); 
                    
                } 
                
            }  
        }
    }//GEN-LAST:event_txtcedulaKeyPressed

    private void txtbonoproduccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbonoproduccionKeyPressed
        //Nos permite que con solo la tecla enter continue al siguiente campo
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String idioma;
            idioma=boxidioma.getSelectedItem().toString();
            //Nos permite validar que los campos esten llenos ademas nos permite mostrar el mensaje de error
            if(idioma.equals("English")&&txtbonoproduccion.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);
            }else{
                if (txtbonoproduccion.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Llene Campos ","",JOptionPane.ERROR_MESSAGE);   
                }else{
                 
                txtanticipos.requestFocus();    
                }   
            }  
        }
    }//GEN-LAST:event_txtbonoproduccionKeyPressed

    private void txtanticiposKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanticiposKeyPressed
        // Nos permite que con solo la tecla enter continue al siguiente campo
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String idioma;
            idioma=boxidioma.getSelectedItem().toString();
            //Nos permite validar que los campos esten llenos ademas nos permite mostrar el mensaje de error
            if(idioma.equals("English")&&txtanticipos.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);
            }else{
                if (txtanticipos.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Llene Campos ","",JOptionPane.ERROR_MESSAGE);   
                }else{
                 
                txtsancion.requestFocus();    
                }   
            }  
        }
    }//GEN-LAST:event_txtanticiposKeyPressed

    private void boxtecnicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxtecnicoKeyPressed
        // Nos permite que con solo la tecla enter continue al siguiente campo
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String tecnico;
            String idioma;
            tecnico=boxtecnico.getSelectedItem().toString();
            idioma=boxidioma.getSelectedItem().toString();
            //Nos permite validar que los campos esten llenos ademas nos permite mostrar el mensaje de error
            if((idioma.equals("English"))&&(tecnico.equals("Cargo"))||(tecnico.equals("Position"))){
                JOptionPane.showMessageDialog(null," ERROR select a charge ","",JOptionPane.ERROR_MESSAGE);
            }else{
                if ((tecnico.equals("Cargo"))||(tecnico.equals("Position"))){
                JOptionPane.showMessageDialog(null," ERROR seleccione un cargo ","",JOptionPane.ERROR_MESSAGE);   
                }else{ 
                 txthorasextras.requestFocus();  
                } 
            }
        }
    }//GEN-LAST:event_boxtecnicoKeyPressed

    private void txtsancionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsancionKeyPressed
        // Nos permite que con solo la tecla enter continue al siguiente campo
        
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){  
            String idioma;
            idioma=boxidioma.getSelectedItem().toString();
            //Nos permite validar que los campos esten llenos ademas nos permite mostrar el mensaje de error
            if(idioma.equals("English")&&txtsancion.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);
            }else{
                if (txtsancion.getText().equals("")){
                JOptionPane.showMessageDialog(null," ERROR Llene Campos ","",JOptionPane.ERROR_MESSAGE);   
                }else{
                    camposblancos();
                    calculo(); 
                    btnaceptar.requestFocus();
                }   
            }   
        }  
    }//GEN-LAST:event_txtsancionKeyPressed

    private void btnaceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnaceptarKeyPressed
        //  Nos permite que con solo la tecla enter continue al siguiente campo
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnguardar.requestFocus();
        }
    }//GEN-LAST:event_btnaceptarKeyPressed

    private void boxidiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxidiomaActionPerformed
        // este metodo nos permite el cambio de idioma de Esapañol al ingles y viceversa
        idioma();
        
    }//GEN-LAST:event_boxidiomaActionPerformed

    private void btnguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardar1ActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // con este metodo nos permite extrer la imformacion desde un block de notas 
       
        extraer();
        
        
        
    }//GEN-LAST:event_btnbuscarActionPerformed
    // con este metodo nos permite visualisar los datos que se encuentran en los diferentes campos
    //y enviarlos a una jtable y visualisar de mejor manera los datos 
    public  void  mostrar(){
        //creamos una matris y vamos unbicando en cada una 
        //de las celdas los diferentes varables 
        int i;
        String matris [][]= new  String[8][8];
        for (i=0; i<7;i++){
            // ubicamos todos el contenido de los label
            matris[0][0]=lblnombre.getText();
            matris[1][0]=lblapellido.getText();
            matris[2][0]=lblcedula.getText();
            matris[3][0]=lbltecnico.getText();
            matris[4][0]=lblhorasextras.getText();
            // ubicamos los contenidos de todos los Text Field
            matris[0][1]=txtnombres.getText();
            matris[1][1]=txtapellidos.getText();
            matris[2][1]=txtcedula.getText();
            matris[3][1]=txttecnico1.getText();
            matris[4][1]=txthorasextras.getText();
            // ubicamos todos el contenido de los label
            matris[0][2]=lblsueldo.getText();
            matris[1][2]=lblbonoperfil.getText();
            matris[2][2]=lblbonoproduccion1.getText();
            matris[3][2]=lblhorasextras1.getText();
            matris[5][2]=lbltotalingreso.getText();
            // ubicamos los contenidos de todos los Text Field
            matris[0][3]=txtsueldo.getText();
            matris[1][3]=txtbonoperfil.getText();
            matris[2][3]=txtbonoproduccion1.getText();
            matris[3][3]=txthorasextras1.getText();
            matris[5][3]=txttotalingreso.getText();
            // ubicamos los contenidos de todos los label
            matris[0][4]=lblaporteiess.getText();
            matris[1][4]=lblsancion1.getText();
            matris[2][4]=lblanticipos1.getText();
            matris[5][4]=lbltotalegreso.getText();
            // ubicamos los contenidos de todos los Text Field
            matris[0][5]=txtaporteiess.getText();
            matris[1][5]=txtsancion1.getText();
            matris[2][5]=txtanticipos1.getText();
            matris[5][5]=txttotalegreso.getText();
            // ubicamos los contenidos de todos los label
            matris[5][6]=lbltotalrecibir.getText();
            // ubicamos los contenidos de todos los Text Field
            matris[5][7]=txttotalrecibir.getText();
            
            
        }
        tablaempleado.setModel(new javax.swing.table.DefaultTableModel(
            // ubicamos la matris para mostrar todo lo guardado en la tabla    
            matris,
            new String [] {
                "Datos Personales", "            ", "Total Ingreso", "", "Total Egresos", "", "Total Recibir", ""
            }
        ));
        
        
        
    } 
     public  void  limpiar (){
         //con este metodo permitimos limpiar los 
         //espacios una ves llenado vuelvan a limpiarse 
        txtnombres.setText("");// con el seText enviamos lo que quemos que se muestren en las variables asignadas
        txtapellidos.setText("");
        txtcedula.setText("");
        txthorasextras.setText("");
        txtbonoproduccion.setText("");
        txtanticipos.setText("");
        txtsancion.setText("");
        txttecnico1.setText("");
        txtsueldo.setText("");
        txtbonoperfil.setText("");
        txtbonoproduccion1.setText("");
        txthorasextras1.setText("");
        txttotalingreso.setText("");
        txtaporteiess.setText("");
        txtanticipos1.setText("");
        txtsancion1.setText("");
        txttotalegreso.setText("");
        txttotalrecibir.setText("");  
     }
     // con este metodo nos permite realizar el calculo deacuerdo a las reglas del negocio
     public void calculo(){
         //declaramos las diferentes constantes para realizar nuestras validaciones
            String ayudante="Ayudante";
            String junior="Junior";
            String senor="Senor";
            String master="Master";
            String sayudante="Assistant";
            String ssenor="Mr";
            
            String tecnico;
            int n1;
            int bp,at,sa;
            float ti,te,i,he,tr;
            // al combo box de tranformamos a String para realizar las diferentes caondiciones
            tecnico=boxtecnico.getSelectedItem().toString();
            // transformamos a la cadena de caracteres a enteros y poder realizar calculos matematicos
            at= Integer.parseInt(txtanticipos.getText());
            sa= Integer.parseInt(txtsancion.getText());
            n1= Integer.parseInt(txthorasextras.getText());
            bp=Integer.parseInt(txtbonoproduccion.getText());
            //realizamos las condiciones y cumplidas dichas validaciones realizar los procesos correspondiantes
            if(tecnico.equals(ayudante)||tecnico.equals(sayudante)){
                
                he= n1*2;
                ti=385+he+bp;
                i=(ti*9)/100;
                te=i+at+sa;
                tr=ti-te; 
                this.txttecnico1.setText(""+tecnico);
                this.txtanticipos1.setText(""+at);
                this.txtsancion1.setText(""+sa);
                this.txthorasextras1.setText(""+he);
                this.txtsueldo.setText("385");
                this.txtaporteiess.setText(""+i);
                this.txtbonoproduccion1.setText(""+bp);
                this.txtbonoperfil.setText("0");
                this.txttotalingreso.setText(""+ti);
                this.txttotalegreso.setText(""+te);
                this.txttotalrecibir.setText(""+tr);
                // con este metodo a las vez mostramos todos los datos de los campos en la tabla
                mostrar();
                
             //realizamos las condiciones y cumplidas dichas validaciones realizar los procesos correspondiantes   
            } else if(tecnico.equals(junior)) {
                he= n1*4;
                ti=385+he+100+bp;
                i=(ti*9)/100;
                te=i+at+sa;
                tr=ti-te;
                this.txttecnico1.setText(""+tecnico);
                this.txtanticipos1.setText(""+at);
                this.txtsancion1.setText(""+sa);
                this.txthorasextras1.setText(""+he);
                this.txtsueldo.setText("385");
                this.txtaporteiess.setText(""+i);
                this.txtbonoproduccion1.setText(""+bp);
                this.txtbonoperfil.setText("100");
                this.txttotalingreso.setText(""+ti);
                this.txttotalegreso.setText(""+te);
                this.txttotalrecibir.setText(""+tr);
                // con este metodo a las vez mostramos todos los datos de los campos en la tabla
                mostrar();
             //realizamos las condiciones y cumplidas dichas validaciones realizar los procesos correspondiantes   
            }else if(tecnico.equals(senor)||tecnico.equals(ssenor)){
                he= n1*6;
                ti=385+he+300+bp;
                i=(ti*9)/100;
                te=i+at+sa;
                tr=ti-te;
                this.txttecnico1.setText(""+tecnico);
                this.txtanticipos1.setText(""+at);
                this.txtsancion1.setText(""+sa);
                this.txthorasextras1.setText(""+he);
                this.txtsueldo.setText("385");
                this.txtaporteiess.setText(""+i);
                this.txtbonoproduccion1.setText(""+bp);
                this.txtbonoperfil.setText("300");
                this.txttotalingreso.setText(""+ti);
                this.txttotalegreso.setText(""+te);
                this.txttotalrecibir.setText(""+tr);
                // con este metodo a las vez mostramos todos los datos de los campos en la tabla
                mostrar();
                
            }else if(tecnico.equals(master)){
                he= n1*8;
                ti=385+he+500+bp;
                i=(ti*9)/100;
                
                te=i+at+sa;
                tr=ti-te; 
                this.txttecnico1.setText(""+tecnico);
                this.txtanticipos1.setText(""+at);
                this.txtsancion1.setText(""+sa);
                this.txthorasextras1.setText(""+he);
                this.txtsueldo.setText("385");
                this.txtaporteiess.setText(""+i);
                this.txtbonoproduccion1.setText(""+bp);
                this.txtbonoperfil.setText("500");
                this.txttotalingreso.setText(""+ti);
                this.txttotalegreso.setText(""+te);
                this.txttotalrecibir.setText(""+tr);
                // con este metodo a las vez mostramos todos los datos de los campos en la tabla
                mostrar();   
            }
         
     }
     // con este metodo realizamos la validacion del numero de la cedula
     public void validacionCedula(){
         Scanner obj=new Scanner(System.in);
            int sim=0,spa=0,dob=0,res=0,st,m,dig;
            int ver,ver1;
            String ced;
            ced= txtcedula.getText();
            int C[]=new int[ced.length()];
            for(int i=0;i<ced.length();i++){
                C[i]=Integer.parseInt(String.valueOf(ced.charAt(i)));
            }
            for(int i=0;i<ced.length()-1;i++){
                if(i%2!=0){
                sim=sim+C[i];
                }else{
                    dob=C[i]*2;
                    if(dob>9){
                        res=dob-9;
                        spa=spa+res;
                    }else{
                        spa=spa+dob;
                    }   
                }
            }
            st=spa+sim;
            ver=st%10;
            if(ver==0){
            }else{
                ver1=10-ver;
                int s = ver1+st;
                if(ver1==C[9]){
                boxtecnico.requestFocus();
                }else{
                    JOptionPane.showMessageDialog(null," ERROR Cedula Incorrecta","",JOptionPane.ERROR_MESSAGE);
                }
            } 
     }
     // con este metodo validamos los campos en blancos y nos envie un mensaje de alvertenncia
     public void camposblancos(){
        String tecnico;
        String idioma;
        idioma=boxidioma.getSelectedItem().toString();
        tecnico=boxtecnico.getSelectedItem().toString();
        if(idioma.equals("English")){
            if ((txtnombres.getText().equals(""))||(txtapellidos.getText().equals(""))){
            JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);   
            }else if((txtcedula.getText().equals(""))||(txthorasextras.getText().equals(""))){
                JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);  
            }else if((txtbonoproduccion.getText().equals(""))||(txtanticipos.getText().equals(""))){
                JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);
            }else if(txtsancion.getText().equals("")||(tecnico.equals("Cargo"))||(tecnico.equals("Position"))){
                JOptionPane.showMessageDialog(null," ERROR Fill Fields ","",JOptionPane.ERROR_MESSAGE);

            }   
        }else{
            if ((txtnombres.getText().equals(""))||(txtapellidos.getText().equals(""))){
            JOptionPane.showMessageDialog(null," ERROR Llene Campos ","",JOptionPane.ERROR_MESSAGE);   
            }else if((txtcedula.getText().equals(""))||(txthorasextras.getText().equals(""))){
                JOptionPane.showMessageDialog(null," ERROR Llene Campos ","",JOptionPane.ERROR_MESSAGE);  
            }else if((txtbonoproduccion.getText().equals(""))||(txtanticipos.getText().equals(""))){
                JOptionPane.showMessageDialog(null," ERROR Llene Campos ","",JOptionPane.ERROR_MESSAGE);
            }else if(txtsancion.getText().equals("")||(tecnico.equals("Cargo"))||(tecnico.equals("Position"))){
                JOptionPane.showMessageDialog(null," ERROR seleccione cargo ","",JOptionPane.ERROR_MESSAGE);

            }else{
              calculo();  
            }   
        }
     }
     // este metodo nos permite realizar el cambio de idioma del sitema
     public void idioma(){
         String idioma;
        // combo box le trasformamos a String par alas diferentes validaciones  
        idioma=boxidioma.getSelectedItem().toString();
        //realizamos las condiciones y aplicara lo cantenido en su interior
        if(idioma.equals("Español")||idioma.equals("Spanish")){
            lblidioma.setText("Idioma");
            boxidioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
            lblnombre.setText("Nombres");
            lblapellido.setText("Apellidos");
            lblcedula.setText("Cedula");
            boxtecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargo", "Ayudante","Junior","Señor","Master" }));
            lbltecnico.setText("Tecnico");
            lblhorasextras.setText("Horas ");
            lblbonoproduccion.setText("Bono Producción");
            lblanticipos.setText("Anticipos");
            lblsancion.setText("Sanción");
            btnaceptar.setText("Aceptar");
            btnguardar.setText("Guardar");
            lblsueldo.setText("Sueldo");
            lblbonoperfil.setText("Bono Perfil");
            lblhorasextras1.setText("Horas extras");
            lblbonoproduccion1.setText("Bono Producción");
            lbltotalingreso.setText("Total Ingreso");
            lbltecnico1.setText("Tecnico");
            lblaporteiess.setText("Aporte IESS");
            lblsancion1.setText("Sanción");
            lblanticipos1.setText("Anticipos");
            lbltotalegreso.setText("Total Egreso");
            lbltotalrecibir.setText("Total recibir");
        }
        else{
            if(idioma.equals("Ingles")){
                lblidioma.setText("Language");
                boxidioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Spanish" }));
                lblnombre.setText("Name");
                lblapellido.setText("Last Name");
                lblcedula.setText("Identification Card");
                boxtecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Position", "Assistant","Junior","Mr","Master" }));
                lbltecnico.setText("Technical");
                lblhorasextras.setText("Hours");
                lblbonoproduccion.setText("Production Bonus");
                lblanticipos.setText("Advances");
                lblsancion.setText("Sanction");
                btnaceptar.setText("To Accept");
                btnguardar.setText("Save");

                lblsueldo.setText("Salary");
                lblbonoperfil.setText("Profile Bonus");
                lblhorasextras1.setText("Extra Hours");
                lblbonoproduccion1.setText("Production Bonus");
                lbltotalingreso.setText("Total Income");
                lbltecnico1.setText("Technical");
                lblaporteiess.setText("IESS Contribution");
                lblsancion1.setText("Sanction");
                lblanticipos1.setText("Advances");
                lbltotalegreso.setText("Total Egress");
                lbltotalrecibir.setText("Total Receive");
                
            }
        }
     }
     // este metodo nos permite guardar los datos del del usuario en un bock de notas 
     // y asi tener registro del usuarios ingresados todos sus datos
     public void guardar(){
         // el archivo guardado se nos inicialisara con el numero de cedula ingresado en el campo
        String archivo= txtcedula.getText()+(".registros");
        File crea_ubicacion=new File(ubicacion);
        File crear_archivo=new File(ubicacion+archivo);
        try{
           // guardamos en forma ordenada los diferentes datos  
            crea_ubicacion.mkdir();
            Formatter crea=new Formatter(ubicacion+archivo);
            crea.format(" Nombres = "+txtnombres.getText()+"\r\n"+
                    "Apellidos = "+ txtapellidos.getText()+"\r\n"+
                    "Cedula = "+txtcedula.getText()+"\r\n"+
                    "Tecnico = "+txttecnico1.getText()+"\r\n"+"\r\n"+
                    "horas = "+txthorasextras.getText()+"\r\n"+
                    //salto linea
                    "Sueldo = "+txtsueldo.getText()+"\r\n"+
                    "bono perfil = "+txtbonoperfil.getText()+"\r\n"+
                    "Bonos = "+txtbonoproduccion.getText()+"\r\n"+
                    "Horas Extras = "+txthorasextras1.getText()+"\r\n"+
                    "Tolal ingreso = "+txttotalingreso.getText()+"\r\n"+"\r\n"+
                
                    "Aporte IESS = "+txtaporteiess.getText()+"\r\n"+
                    "Sancion = "+txtsancion1.getText()+"\r\n"+
                    "Anticipos = "+txtanticipos1.getText()+"\r\n"+
                    "Total Egreso = "+txttotalegreso.getText()+"\r\n"+"\r\n"+
                
                    " Total recibir = "+txttotalrecibir.getText());
        
                    crea.close();
                    limpiar();
                    mostrar();
        }catch(Exception e){
            
        }
    }
     // Con este metodo nos permite extraer nuevamente los datos guardados hacia el jframe 
     public void extraer (){
         // ubicando el numero de cedula el campo correspondiente se nos despliega la informacion guardado
         File url =new File(ubicacion+txtcedula.getText()+".registros");
         if(txtcedula.getText().equals("")){
             JOptionPane.showMessageDialog(null,"\t INDIQUE CEDULA"+"","",JOptionPane.INFORMATION_MESSAGE);
         }else {
             if(url.exists()){
                 //JOptionPane.showMessageDialog(null,"\t no esxiste"+"","",JOptionPane.INFORMATION_MESSAGE);
                 try {
                     // estos seran todos los datos que nos desplegara en el jframe
                     FileInputStream fis=new FileInputStream(url);
                     Properties exportar=new Properties();
                     exportar.load(fis);
                     txtnombres.setText(exportar.getProperty("Nombres"));
                     txtapellidos.setText(exportar.getProperty("Apellidos"));
                     txtcedula.setText(exportar.getProperty("Cedula"));
                     txthorasextras.setText(exportar.getProperty("horas"));
                     txtbonoproduccion.setText(exportar.getProperty("Bonos"));
                     txtanticipos.setText(exportar.getProperty("Anticipos"));
                     txtsancion.setText(exportar.getProperty("Sancion"));
                     txttecnico1.setText(exportar.getProperty("Tecnico"));
                     
                     
                 }catch (Exception e){
                     
                 }
                 
             }
         }
         
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxidioma;
    private javax.swing.JComboBox<String> boxtecnico;
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnbuscar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnguardar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblanticipos;
    private javax.swing.JLabel lblanticipos1;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblaporteiess;
    private javax.swing.JLabel lblbonoperfil;
    private javax.swing.JLabel lblbonoproduccion;
    private javax.swing.JLabel lblbonoproduccion1;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblhorasextras;
    private javax.swing.JLabel lblhorasextras1;
    private javax.swing.JLabel lblidioma;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblsancion;
    private javax.swing.JLabel lblsancion1;
    private javax.swing.JLabel lblsueldo;
    private javax.swing.JLabel lbltecnico;
    private javax.swing.JLabel lbltecnico1;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JLabel lbltotalegreso;
    private javax.swing.JLabel lbltotalingreso;
    private javax.swing.JLabel lbltotalrecibir;
    public javax.swing.JTable tablaempleado;
    private javax.swing.JTextField txtanticipos;
    private javax.swing.JTextField txtanticipos1;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtaporteiess;
    private javax.swing.JTextField txtbonoperfil;
    private javax.swing.JTextField txtbonoproduccion;
    private javax.swing.JTextField txtbonoproduccion1;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txthorasextras;
    private javax.swing.JTextField txthorasextras1;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtsancion;
    private javax.swing.JTextField txtsancion1;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txttecnico1;
    private javax.swing.JTextField txttotalegreso;
    private javax.swing.JTextField txttotalingreso;
    private javax.swing.JTextField txttotalrecibir;
    // End of variables declaration//GEN-END:variables

    private String AbrirArchivo(File archivo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    
}
